export const reviewData = [

    // =================================================
    // RATING ONLY
    // 200 REVIEWS
    // =================================================

    { reviewIndex: 0, rating: 5 },
    { reviewIndex: 1, rating: 5 },
    { reviewIndex: 2, rating: 4 },
    { reviewIndex: 3, rating: 5 },
    { reviewIndex: 4, rating: 4 },
    { reviewIndex: 5, rating: 5 },
    { reviewIndex: 6, rating: 5 },
    { reviewIndex: 7, rating: 4 },
    { reviewIndex: 8, rating: 3 },
    { reviewIndex: 9, rating: 5 },

    { reviewIndex: 10, rating: 5 },
    { reviewIndex: 11, rating: 4 },
    { reviewIndex: 12, rating: 5 },
    { reviewIndex: 13, rating: 4 },
    { reviewIndex: 14, rating: 3 },
    { reviewIndex: 15, rating: 5 },
    { reviewIndex: 16, rating: 4 },
    { reviewIndex: 17, rating: 5 },
    { reviewIndex: 18, rating: 5 },
    { reviewIndex: 19, rating: 4 },

    { reviewIndex: 20, rating: 5 },
    { reviewIndex: 21, rating: 4 },
    { reviewIndex: 22, rating: 3 },
    { reviewIndex: 23, rating: 5 },
    { reviewIndex: 24, rating: 4 },
    { reviewIndex: 25, rating: 5 },
    { reviewIndex: 26, rating: 5 },
    { reviewIndex: 27, rating: 4 },
    { reviewIndex: 28, rating: 5 },
    { reviewIndex: 29, rating: 3 },

    { reviewIndex: 30, rating: 5 },
    { reviewIndex: 31, rating: 4 },
    { reviewIndex: 32, rating: 5 },
    { reviewIndex: 33, rating: 4 },
    { reviewIndex: 34, rating: 5 },
    { reviewIndex: 35, rating: 5 },
    { reviewIndex: 36, rating: 3 },
    { reviewIndex: 37, rating: 4 },
    { reviewIndex: 38, rating: 5 },
    { reviewIndex: 39, rating: 4 },

    { reviewIndex: 40, rating: 5 },
    { reviewIndex: 41, rating: 5 },
    { reviewIndex: 42, rating: 4 },
    { reviewIndex: 43, rating: 3 },
    { reviewIndex: 44, rating: 5 },
    { reviewIndex: 45, rating: 4 },
    { reviewIndex: 46, rating: 5 },
    { reviewIndex: 47, rating: 4 },
    { reviewIndex: 48, rating: 5 },
    { reviewIndex: 49, rating: 5 },

    { reviewIndex: 50, rating: 4 },
    { reviewIndex: 51, rating: 5 },
    { reviewIndex: 52, rating: 5 },
    { reviewIndex: 53, rating: 3 },
    { reviewIndex: 54, rating: 4 },
    { reviewIndex: 55, rating: 5 },
    { reviewIndex: 56, rating: 4 },
    { reviewIndex: 57, rating: 5 },
    { reviewIndex: 58, rating: 5 },
    { reviewIndex: 59, rating: 4 },

    { reviewIndex: 60, rating: 5 },
    { reviewIndex: 61, rating: 4 },
    { reviewIndex: 62, rating: 5 },
    { reviewIndex: 63, rating: 3 },
    { reviewIndex: 64, rating: 5 },
    { reviewIndex: 65, rating: 4 },
    { reviewIndex: 66, rating: 5 },
    { reviewIndex: 67, rating: 4 },
    { reviewIndex: 68, rating: 5 },
    { reviewIndex: 69, rating: 5 },

    { reviewIndex: 70, rating: 4 },
    { reviewIndex: 71, rating: 5 },
    { reviewIndex: 72, rating: 3 },
    { reviewIndex: 73, rating: 4 },
    { reviewIndex: 74, rating: 5 },
    { reviewIndex: 75, rating: 5 },
    { reviewIndex: 76, rating: 4 },
    { reviewIndex: 77, rating: 5 },
    { reviewIndex: 78, rating: 4 },
    { reviewIndex: 79, rating: 5 },

    { reviewIndex: 80, rating: 5 },
    { reviewIndex: 81, rating: 4 },
    { reviewIndex: 82, rating: 3 },
    { reviewIndex: 83, rating: 5 },
    { reviewIndex: 84, rating: 4 },
    { reviewIndex: 85, rating: 5 },
    { reviewIndex: 86, rating: 5 },
    { reviewIndex: 87, rating: 4 },
    { reviewIndex: 88, rating: 5 },
    { reviewIndex: 89, rating: 3 },

    { reviewIndex: 90, rating: 5 },
    { reviewIndex: 91, rating: 4 },
    { reviewIndex: 92, rating: 5 },
    { reviewIndex: 93, rating: 5 },
    { reviewIndex: 94, rating: 4 },
    { reviewIndex: 95, rating: 3 },
    { reviewIndex: 96, rating: 5 },
    { reviewIndex: 97, rating: 4 },
    { reviewIndex: 98, rating: 5 },
    { reviewIndex: 99, rating: 5 },

    { reviewIndex: 100, rating: 4 },
    { reviewIndex: 101, rating: 5 },
    { reviewIndex: 102, rating: 5 },
    { reviewIndex: 103, rating: 4 },
    { reviewIndex: 104, rating: 3 },
    { reviewIndex: 105, rating: 5 },
    { reviewIndex: 106, rating: 4 },
    { reviewIndex: 107, rating: 5 },
    { reviewIndex: 108, rating: 5 },
    { reviewIndex: 109, rating: 4 },

    { reviewIndex: 110, rating: 5 },
    { reviewIndex: 111, rating: 3 },
    { reviewIndex: 112, rating: 4 },
    { reviewIndex: 113, rating: 5 },
    { reviewIndex: 114, rating: 4 },
    { reviewIndex: 115, rating: 5 },
    { reviewIndex: 116, rating: 5 },
    { reviewIndex: 117, rating: 4 },
    { reviewIndex: 118, rating: 3 },
    { reviewIndex: 119, rating: 5 },

    { reviewIndex: 120, rating: 4 },
    { reviewIndex: 121, rating: 5 },
    { reviewIndex: 122, rating: 5 },
    { reviewIndex: 123, rating: 4 },
    { reviewIndex: 124, rating: 5 },
    { reviewIndex: 125, rating: 3 },
    { reviewIndex: 126, rating: 4 },
    { reviewIndex: 127, rating: 5 },
    { reviewIndex: 128, rating: 5 },
    { reviewIndex: 129, rating: 4 },

    { reviewIndex: 130, rating: 5 },
    { reviewIndex: 131, rating: 4 },
    { reviewIndex: 132, rating: 5 },
    { reviewIndex: 133, rating: 3 },
    { reviewIndex: 134, rating: 5 },
    { reviewIndex: 135, rating: 4 },
    { reviewIndex: 136, rating: 5 },
    { reviewIndex: 137, rating: 5 },
    { reviewIndex: 138, rating: 4 },
    { reviewIndex: 139, rating: 5 },

    { reviewIndex: 140, rating: 4 },
    { reviewIndex: 141, rating: 5 },
    { reviewIndex: 142, rating: 5 },
    { reviewIndex: 143, rating: 3 },
    { reviewIndex: 144, rating: 4 },
    { reviewIndex: 145, rating: 5 },
    { reviewIndex: 146, rating: 5 },
    { reviewIndex: 147, rating: 4 },
    { reviewIndex: 148, rating: 5 },
    { reviewIndex: 149, rating: 4 },

    { reviewIndex: 150, rating: 5 },
    { reviewIndex: 151, rating: 4 },
    { reviewIndex: 152, rating: 5 },
    { reviewIndex: 153, rating: 3 },
    { reviewIndex: 154, rating: 5 },
    { reviewIndex: 155, rating: 4 },
    { reviewIndex: 156, rating: 5 },
    { reviewIndex: 157, rating: 5 },
    { reviewIndex: 158, rating: 4 },
    { reviewIndex: 159, rating: 5 },

    { reviewIndex: 160, rating: 4 },
    { reviewIndex: 161, rating: 5 },
    { reviewIndex: 162, rating: 3 },
    { reviewIndex: 163, rating: 5 },
    { reviewIndex: 164, rating: 4 },
    { reviewIndex: 165, rating: 5 },
    { reviewIndex: 166, rating: 5 },
    { reviewIndex: 167, rating: 4 },
    { reviewIndex: 168, rating: 5 },
    { reviewIndex: 169, rating: 3 },

    { reviewIndex: 170, rating: 5 },
    { reviewIndex: 171, rating: 4 },
    { reviewIndex: 172, rating: 5 },
    { reviewIndex: 173, rating: 4 },
    { reviewIndex: 174, rating: 5 },
    { reviewIndex: 175, rating: 3 },
    { reviewIndex: 176, rating: 4 },
    { reviewIndex: 177, rating: 5 },
    { reviewIndex: 178, rating: 5 },
    { reviewIndex: 179, rating: 4 },

    { reviewIndex: 180, rating: 5 },
    { reviewIndex: 181, rating: 4 },
    { reviewIndex: 182, rating: 3 },
    { reviewIndex: 183, rating: 5 },
    { reviewIndex: 184, rating: 4 },
    { reviewIndex: 185, rating: 5 },
    { reviewIndex: 186, rating: 5 },
    { reviewIndex: 187, rating: 4 },
    { reviewIndex: 188, rating: 5 },
    { reviewIndex: 189, rating: 3 },

    { reviewIndex: 190, rating: 5 },
    { reviewIndex: 191, rating: 4 },
    { reviewIndex: 192, rating: 5 },
    { reviewIndex: 193, rating: 4 },
    { reviewIndex: 194, rating: 5 },
    { reviewIndex: 195, rating: 3 },
    { reviewIndex: 196, rating: 5 },
    { reviewIndex: 197, rating: 4 },
    { reviewIndex: 198, rating: 5 },
    { reviewIndex: 199, rating: 2 },


    // =================================================
    // RATING + COMMENT
    // 300 REVIEWS
    // =================================================

    { reviewIndex: 200, rating: 5, comment: "خیلی خوشمزه بود، مخصوصاً طعم سسش. دوباره سفارش می‌دم." },
    { reviewIndex: 201, rating: 5, comment: "غذا تازه و گرم رسید و حجمش هم کاملاً مناسب بود." },
    { reviewIndex: 202, rating: 4, comment: "طعمش خوب بود، فقط کمی دیرتر از چیزی که انتظار داشتم رسید." },
    { reviewIndex: 203, rating: 5, comment: "واقعاً راضی بودم. همه چیز مرتب و تازه بود." },
    { reviewIndex: 204, rating: 4, comment: "خوش‌طعم بود و بسته‌بندی خوبی هم داشت." },
    { reviewIndex: 205, rating: 5, comment: "یکی از بهترین سفارش‌هایی بود که از اینجا داشتم." },
    { reviewIndex: 206, rating: 3, comment: "بد نبود، ولی انتظار داشتم غذا کمی گرم‌تر باشد." },
    { reviewIndex: 207, rating: 5, comment: "طعم غذا خیلی خوب بود و مقدارش هم کافی بود." },
    { reviewIndex: 208, rating: 4, comment: "در کل خوب بود، فقط نمکش کمی زیاد بود." },
    { reviewIndex: 209, rating: 5, comment: "خیلی خوب و تازه بود. مخصوصاً کنار غذا خیلی چسبید." },

    { reviewIndex: 210, rating: 5, comment: "همه چیز دقیقاً طبق سفارشم بود و چیزی کم نداشت." },
    { reviewIndex: 211, rating: 4, comment: "کیفیت خوب بود و بسته‌بندی هم تمیز و مرتب رسید." },
    { reviewIndex: 212, rating: 5, comment: "طعمش عالی بود، حتماً دوباره امتحانش می‌کنم." },
    { reviewIndex: 213, rating: 3, comment: "طعمش معمولی بود. نه بد بود نه خیلی خاص." },
    { reviewIndex: 214, rating: 5, comment: "خیلی تازه بود و معلوم بود تازه آماده شده." },
    { reviewIndex: 215, rating: 4, comment: "خوب بود، فقط مقدار سس می‌توانست بیشتر باشد." },
    { reviewIndex: 216, rating: 5, comment: "از کیفیت غذا واقعاً راضی بودم." },
    { reviewIndex: 217, rating: 5, comment: "گرم به دستم رسید و طعمش هم عالی بود." },
    { reviewIndex: 218, rating: 4, comment: "سفارش خوب و قابل قبولی بود." },
    { reviewIndex: 219, rating: 5, comment: "خیلی خوش‌طعم بود و حجمش هم خوب بود." },

    { reviewIndex: 220, rating: 4, comment: "طعم خوبی داشت ولی کمی شور بود." },
    { reviewIndex: 221, rating: 5, comment: "خیلی راضی بودم، کیفیت غذا واقعاً خوب بود." },
    { reviewIndex: 222, rating: 3, comment: "نسبت به قیمتش می‌توانست کمی بیشتر باشد." },
    { reviewIndex: 223, rating: 5, comment: "عالی بود، مخصوصاً وقتی گرم بود خیلی خوشمزه شد." },
    { reviewIndex: 224, rating: 4, comment: "در مجموع سفارش خوبی بود و دوباره می‌گیرم." },
    { reviewIndex: 225, rating: 5, comment: "طعمش خیلی خوب بود و اصلاً چرب و سنگین نبود." },
    { reviewIndex: 226, rating: 4, comment: "کیفیت خوب بود، فقط زمان ارسال کمی طولانی شد." },
    { reviewIndex: 227, rating: 5, comment: "واقعاً خوشمزه بود. از چیزی که انتظار داشتم بهتر بود." },
    { reviewIndex: 228, rating: 5, comment: "هم غذا خوب بود هم بسته‌بندی تمیز و مناسب بود." },
    { reviewIndex: 229, rating: 3, comment: "بد نبود، ولی فکر می‌کنم می‌توانست طعم بهتری داشته باشد." },

    { reviewIndex: 230, rating: 5, comment: "خیلی خوب بود، مخصوصاً طعم ادویه‌ها کاملاً مناسب بود." },
    { reviewIndex: 231, rating: 4, comment: "غذا خوشمزه بود و مقدارش هم مناسب بود." },
    { reviewIndex: 232, rating: 5, comment: "سفارش سریع رسید و غذا هنوز کاملاً گرم بود." },
    { reviewIndex: 233, rating: 4, comment: "خوب بود، فقط کمی خشک شده بود." },
    { reviewIndex: 234, rating: 5, comment: "همه چیز تازه و خوش‌طعم بود." },
    { reviewIndex: 235, rating: 5, comment: "خیلی دوست داشتم، مخصوصاً ترکیب طعم‌ها." },
    { reviewIndex: 236, rating: 3, comment: "متوسط بود و چیز خاصی نداشت." },
    { reviewIndex: 237, rating: 4, comment: "در کل راضی بودم و دوباره سفارش می‌دهم." },
    { reviewIndex: 238, rating: 5, comment: "خیلی خوشمزه و تازه بود." },
    { reviewIndex: 239, rating: 5, comment: "کیفیت غذا واقعاً خوب بود و حجمش هم مناسب بود." },

    { reviewIndex: 240, rating: 4, comment: "طعم خوب بود ولی کمی سرد شده بود." },
    { reviewIndex: 241, rating: 5, comment: "عالی بود، از سفارشم کاملاً راضی هستم." },
    { reviewIndex: 242, rating: 4, comment: "غذا خوب بود و بسته‌بندی هم مناسب بود." },
    { reviewIndex: 243, rating: 5, comment: "طعم خیلی خوبی داشت و دوباره سفارش می‌دم." },
    { reviewIndex: 244, rating: 3, comment: "قابل قبول بود ولی می‌توانست بهتر باشد." },
    { reviewIndex: 245, rating: 5, comment: "خیلی تازه و خوشمزه بود." },
    { reviewIndex: 246, rating: 4, comment: "کیفیت خوب بود، فقط کمی ادویه‌اش زیاد بود." },
    { reviewIndex: 247, rating: 5, comment: "یکی از سفارش‌های خوبم بود، همه چیز درست و مرتب رسید." },
    { reviewIndex: 248, rating: 5, comment: "واقعاً خوشمزه بود و حجم مناسبی هم داشت." },
    { reviewIndex: 249, rating: 4, comment: "در مجموع تجربه خوبی بود." },

    { reviewIndex: 250, rating: 5, comment: "غذا خیلی خوب آماده شده بود و طعمش عالی بود." },
    { reviewIndex: 251, rating: 4, comment: "خوب بود، فقط کمی روغنی بود." },
    { reviewIndex: 252, rating: 5, comment: "خیلی راضی بودم. همه چیز تازه و گرم رسید." },
    { reviewIndex: 253, rating: 3, comment: "طعم معمولی داشت و خیلی تحت تأثیر قرار نگرفتم." },
    { reviewIndex: 254, rating: 5, comment: "خیلی خوش‌طعم بود و کیفیتش مشخص بود." },
    { reviewIndex: 255, rating: 4, comment: "نسبت به قیمت کیفیت مناسبی داشت." },
    { reviewIndex: 256, rating: 5, comment: "عالی و خوشمزه بود، دوباره می‌گیرمش." },
    { reviewIndex: 257, rating: 5, comment: "هم داغ رسید هم مزه خیلی خوبی داشت." },
    { reviewIndex: 258, rating: 4, comment: "خوب بود، فقط کمی زمان ارسال بیشتر شد." },
    { reviewIndex: 259, rating: 5, comment: "از این سفارش خیلی راضی بودم." },

    { reviewIndex: 260, rating: 5, comment: "طعمش واقعاً عالی بود و کاملاً تازه به نظر می‌رسید." },
    { reviewIndex: 261, rating: 4, comment: "کیفیت خوب بود و مقدار غذا هم کافی بود." },
    { reviewIndex: 262, rating: 5, comment: "خیلی خوشمزه بود، مخصوصاً وقتی تازه رسید." },
    { reviewIndex: 263, rating: 3, comment: "در حد انتظار بود، نه بیشتر." },
    { reviewIndex: 264, rating: 5, comment: "همه چیز مرتب و بدون مشکل به دستم رسید." },
    { reviewIndex: 265, rating: 4, comment: "طعمش خوب بود ولی کمی شور بود." },
    { reviewIndex: 266, rating: 5, comment: "واقعاً سفارش خوبی بود." },
    { reviewIndex: 267, rating: 5, comment: "حجمش خوب بود و کیفیت غذا هم عالی بود." },
    { reviewIndex: 268, rating: 4, comment: "خوشمزه بود، فقط انتظار داشتم کمی بیشتر باشد." },
    { reviewIndex: 269, rating: 5, comment: "خیلی راضی بودم و احتمالاً دوباره سفارش می‌دم." },

    { reviewIndex: 270, rating: 5, comment: "غذا تازه بود و طعمش خیلی خوب بود." },
    { reviewIndex: 271, rating: 4, comment: "سفارش خوبی بود و همه چیز درست ارسال شده بود." },
    { reviewIndex: 272, rating: 3, comment: "کیفیت قابل قبول بود ولی عالی نبود." },
    { reviewIndex: 273, rating: 5, comment: "خیلی خوشمزه بود و از انتخابم راضی هستم." },
    { reviewIndex: 274, rating: 4, comment: "خوب بود، ولی مقدار سس کم بود." },
    { reviewIndex: 275, rating: 5, comment: "طعمش عالی بود و غذا هم گرم رسید." },
    { reviewIndex: 276, rating: 5, comment: "خیلی بهتر از چیزی بود که انتظار داشتم." },
    { reviewIndex: 277, rating: 4, comment: "در کل خوب بود و مشکل خاصی نداشت." },
    { reviewIndex: 278, rating: 5, comment: "کیفیت خیلی خوبی داشت." },
    { reviewIndex: 279, rating: 3, comment: "متوسط بود، شاید دوباره امتحانش کنم." },

    { reviewIndex: 280, rating: 5, comment: "خیلی خوش‌طعم و تازه بود." },
    { reviewIndex: 281, rating: 4, comment: "غذا خوب بود، فقط کمی خشک شده بود." },
    { reviewIndex: 282, rating: 5, comment: "واقعاً راضی بودم و همه چیز مرتب بود." },
    { reviewIndex: 283, rating: 5, comment: "طعمش عالی بود و حجم خوبی هم داشت." },
    { reviewIndex: 284, rating: 4, comment: "سفارش خوبی بود و به‌موقع رسید." },
    { reviewIndex: 285, rating: 3, comment: "بد نبود ولی انتظار بیشتری داشتم." },
    { reviewIndex: 286, rating: 5, comment: "خیلی تازه و خوشمزه بود." },
    { reviewIndex: 287, rating: 4, comment: "در مجموع کیفیت خوبی داشت." },
    { reviewIndex: 288, rating: 5, comment: "طعم غذا خیلی خوب بود." },
    { reviewIndex: 289, rating: 5, comment: "از سفارشم کاملاً راضی بودم." },

    { reviewIndex: 290, rating: 4, comment: "خوب بود، فقط کمی شور بود." },
    { reviewIndex: 291, rating: 5, comment: "واقعاً خوشمزه بود و دوباره سفارش می‌دم." },
    { reviewIndex: 292, rating: 3, comment: "قابل قبول بود، ولی خیلی خاص نبود." },
    { reviewIndex: 293, rating: 5, comment: "غذا گرم و تازه رسید." },
    { reviewIndex: 294, rating: 4, comment: "کیفیت مناسبی داشت و ازش راضی بودم." },
    { reviewIndex: 295, rating: 5, comment: "هم طعم خوب بود هم حجم مناسب." },
    { reviewIndex: 296, rating: 4, comment: "سفارش خوب و بدون دردسری بود." },
    { reviewIndex: 297, rating: 5, comment: "خیلی خوشمزه بود، مخصوصاً طعم ادویه‌ها." },
    { reviewIndex: 298, rating: 5, comment: "از کیفیت این سفارش خیلی راضی بودم." },
    { reviewIndex: 299, rating: 4, comment: "خوب بود و احتمالاً دوباره سفارش می‌دم." },

    { reviewIndex: 300, rating: 5, comment: "واقعاً عالی بود و کاملاً تازه به دستم رسید." },
    { reviewIndex: 301, rating: 4, comment: "طعم خوبی داشت و حجمش هم مناسب بود." },
    { reviewIndex: 302, rating: 5, comment: "یکی از سفارش‌های مورد علاقه‌ام شد." },
    { reviewIndex: 303, rating: 3, comment: "معمولی بود و می‌توانست کیفیت بهتری داشته باشد." },
    { reviewIndex: 304, rating: 5, comment: "خیلی خوشمزه و تازه بود." },
    { reviewIndex: 305, rating: 4, comment: "در کل تجربه خوبی بود." },
    { reviewIndex: 306, rating: 5, comment: "بسته‌بندی خوب بود و غذا هم گرم رسید." },
    { reviewIndex: 307, rating: 5, comment: "طعمش واقعاً عالی بود." },
    { reviewIndex: 308, rating: 4, comment: "خوب بود، فقط کمی دیر رسید." },
    { reviewIndex: 309, rating: 5, comment: "خیلی راضی بودم." },

    { reviewIndex: 310, rating: 4, comment: "کیفیت خوب و طعم قابل قبولی داشت." },
    { reviewIndex: 311, rating: 5, comment: "خیلی خوشمزه بود و حجم خوبی داشت." },
    { reviewIndex: 312, rating: 5, comment: "همه چیز مرتب و تازه بود." },
    { reviewIndex: 313, rating: 3, comment: "بد نبود ولی خیلی هم فوق‌العاده نبود." },
    { reviewIndex: 314, rating: 4, comment: "طعم خوب بود ولی کمی چرب بود." },
    { reviewIndex: 315, rating: 5, comment: "خیلی خوب بود و دوباره سفارش می‌دم." },
    { reviewIndex: 316, rating: 5, comment: "غذا داغ و خوش‌طعم رسید." },
    { reviewIndex: 317, rating: 4, comment: "در مجموع راضی بودم." },
    { reviewIndex: 318, rating: 5, comment: "کیفیت غذا واقعاً خوب بود." },
    { reviewIndex: 319, rating: 5, comment: "خیلی خوشمزه بود." },

    { reviewIndex: 320, rating: 4, comment: "خوب بود، فقط مقدارش کمی کم بود." },
    { reviewIndex: 321, rating: 5, comment: "طعم خیلی خوبی داشت و تازه بود." },
    { reviewIndex: 322, rating: 3, comment: "قابل قبول بود اما انتظار بیشتری داشتم." },
    { reviewIndex: 323, rating: 5, comment: "همه چیز عالی و مرتب بود." },
    { reviewIndex: 324, rating: 4, comment: "طعم خوبی داشت و بسته‌بندی هم مناسب بود." },
    { reviewIndex: 325, rating: 5, comment: "خیلی راضی بودم، مخصوصاً از کیفیت غذا." },
    { reviewIndex: 326, rating: 5, comment: "واقعاً خوشمزه و تازه بود." },
    { reviewIndex: 327, rating: 4, comment: "خوب بود و به موقع رسید." },
    { reviewIndex: 328, rating: 5, comment: "یکی از سفارش‌های خوبم بود." },
    { reviewIndex: 329, rating: 4, comment: "کیفیت مناسبی داشت." },

    { reviewIndex: 330, rating: 5, comment: "طعمش خیلی خوب بود و کاملاً راضی بودم." },
    { reviewIndex: 331, rating: 4, comment: "خوب بود، فقط کمی نمک بیشتری داشت." },
    { reviewIndex: 332, rating: 5, comment: "غذا گرم و تازه رسید." },
    { reviewIndex: 333, rating: 3, comment: "متوسط بود و خیلی خاص نبود." },
    { reviewIndex: 334, rating: 5, comment: "خیلی خوشمزه بود و حجمش هم مناسب بود." },
    { reviewIndex: 335, rating: 4, comment: "در کل سفارش خوبی بود." },
    { reviewIndex: 336, rating: 5, comment: "کیفیتش واقعاً خوب بود." },
    { reviewIndex: 337, rating: 5, comment: "طعم عالی و بسته‌بندی مرتب بود." },
    { reviewIndex: 338, rating: 4, comment: "خوب بود ولی کمی سرد شده بود." },
    { reviewIndex: 339, rating: 5, comment: "خیلی راضی بودم و دوباره سفارش می‌دم." },

    { reviewIndex: 340, rating: 4, comment: "طعم خوبی داشت و نسبت به قیمت مناسب بود." },
    { reviewIndex: 341, rating: 5, comment: "واقعاً خوشمزه بود." },
    { reviewIndex: 342, rating: 5, comment: "تازه و خوش‌طعم بود." },
    { reviewIndex: 343, rating: 3, comment: "کیفیت متوسط بود." },
    { reviewIndex: 344, rating: 5, comment: "هم حجم مناسب بود هم طعم عالی." },
    { reviewIndex: 345, rating: 4, comment: "سفارش خوبی بود و مشکل خاصی نداشت." },
    { reviewIndex: 346, rating: 5, comment: "از کیفیت غذا خیلی راضی بودم." },
    { reviewIndex: 347, rating: 4, comment: "خوشمزه بود، فقط کمی چرب بود." },
    { reviewIndex: 348, rating: 5, comment: "خیلی تازه و گرم رسید." },
    { reviewIndex: 349, rating: 5, comment: "عالی بود، دوباره حتماً سفارش می‌دم." },

    { reviewIndex: 350, rating: 4, comment: "در مجموع خوب بود و ارزش امتحان کردن دارد." },
    { reviewIndex: 351, rating: 5, comment: "طعمش خیلی خوب بود." },
    { reviewIndex: 352, rating: 3, comment: "بد نبود، ولی می‌توانست بهتر باشد." },
    { reviewIndex: 353, rating: 5, comment: "خیلی خوشمزه و تازه بود." },
    { reviewIndex: 354, rating: 4, comment: "کیفیت خوب و حجم مناسب داشت." },
    { reviewIndex: 355, rating: 5, comment: "کاملاً از سفارشم راضی بودم." },
    { reviewIndex: 356, rating: 5, comment: "هم طعم خوب بود هم غذا گرم رسید." },
    { reviewIndex: 357, rating: 4, comment: "سفارش خوبی بود." },
    { reviewIndex: 358, rating: 5, comment: "خیلی بهتر از چیزی بود که انتظار داشتم." },
    { reviewIndex: 359, rating: 4, comment: "خوشمزه بود ولی کمی شور بود." },

    { reviewIndex: 360, rating: 5, comment: "واقعاً کیفیت خوبی داشت." },
    { reviewIndex: 361, rating: 4, comment: "طعم خوب و حجم مناسبی داشت." },
    { reviewIndex: 362, rating: 5, comment: "خیلی راضی بودم." },
    { reviewIndex: 363, rating: 3, comment: "در حد متوسط بود." },
    { reviewIndex: 364, rating: 5, comment: "تازه و خوش‌طعم بود." },
    { reviewIndex: 365, rating: 4, comment: "بسته‌بندی خوب بود و غذا هم سالم رسید." },
    { reviewIndex: 366, rating: 5, comment: "طعمش عالی بود." },
    { reviewIndex: 367, rating: 5, comment: "خیلی خوشمزه بود و دوباره سفارش می‌دم." },
    { reviewIndex: 368, rating: 4, comment: "خوب بود ولی زمان ارسال کمی طولانی شد." },
    { reviewIndex: 369, rating: 5, comment: "کاملاً راضی بودم." },

    { reviewIndex: 370, rating: 4, comment: "غذا خوشمزه بود و حجم خوبی داشت." },
    { reviewIndex: 371, rating: 5, comment: "خیلی تازه و خوش‌طعم بود." },
    { reviewIndex: 372, rating: 5, comment: "یکی از بهترین سفارش‌هام بود." },
    { reviewIndex: 373, rating: 3, comment: "طعم معمولی داشت." },
    { reviewIndex: 374, rating: 4, comment: "در مجموع خوب و قابل قبول بود." },
    { reviewIndex: 375, rating: 5, comment: "خیلی خوب بود، مخصوصاً از نظر تازگی." },
    { reviewIndex: 376, rating: 5, comment: "طعم عالی و حجم مناسب." },
    { reviewIndex: 377, rating: 4, comment: "خوب بود، فقط کمی سرد شده بود." },
    { reviewIndex: 378, rating: 5, comment: "خیلی خوشمزه بود." },
    { reviewIndex: 379, rating: 4, comment: "کیفیت خوبی داشت." },

    { reviewIndex: 380, rating: 5, comment: "واقعاً راضی بودم و دوباره سفارش می‌دم." },
    { reviewIndex: 381, rating: 4, comment: "طعم خوبی داشت." },
    { reviewIndex: 382, rating: 5, comment: "خیلی تازه بود." },
    { reviewIndex: 383, rating: 3, comment: "بد نبود ولی خیلی خاص هم نبود." },
    { reviewIndex: 384, rating: 5, comment: "غذا گرم و مرتب رسید." },
    { reviewIndex: 385, rating: 4, comment: "خوب بود و حجمش هم مناسب بود." },
    { reviewIndex: 386, rating: 5, comment: "طعمش خیلی خوب بود." },
    { reviewIndex: 387, rating: 5, comment: "از کیفیتش راضی بودم." },
    { reviewIndex: 388, rating: 4, comment: "در کل سفارش خوبی بود." },
    { reviewIndex: 389, rating: 5, comment: "عالی و خوشمزه بود." },

    { reviewIndex: 390, rating: 4, comment: "طعم خوب بود، فقط کمی روغنی بود." },
    { reviewIndex: 391, rating: 5, comment: "خیلی تازه و خوش‌طعم بود." },
    { reviewIndex: 392, rating: 5, comment: "همه چیز خوب و مرتب بود." },
    { reviewIndex: 393, rating: 3, comment: "متوسط بود و انتظار بیشتری داشتم." },
    { reviewIndex: 394, rating: 5, comment: "واقعاً خوشمزه بود." },
    { reviewIndex: 395, rating: 4, comment: "کیفیت خوبی داشت و راضی بودم." },
    { reviewIndex: 396, rating: 5, comment: "غذا گرم رسید و طعمش عالی بود." },
    { reviewIndex: 397, rating: 4, comment: "خوب بود ولی کمی نمک زیاد داشت." },
    { reviewIndex: 398, rating: 5, comment: "خیلی خوب و تازه بود." },
    { reviewIndex: 399, rating: 5, comment: "دوباره حتماً سفارش می‌دم." },

    { reviewIndex: 400, rating: 4, comment: "سفارش خوبی بود و همه چیز درست ارسال شد." },
    { reviewIndex: 401, rating: 5, comment: "طعم خیلی خوبی داشت." },
    { reviewIndex: 402, rating: 3, comment: "قابل قبول بود ولی عالی نبود." },
    { reviewIndex: 403, rating: 5, comment: "خیلی خوشمزه و تازه بود." },
    { reviewIndex: 404, rating: 4, comment: "حجم خوب بود و کیفیت هم مناسب بود." },
    { reviewIndex: 405, rating: 5, comment: "واقعاً از سفارشم راضی بودم." },
    { reviewIndex: 406, rating: 5, comment: "هم گرم بود هم خوش‌طعم." },
    { reviewIndex: 407, rating: 4, comment: "در کل تجربه خوبی بود." },
    { reviewIndex: 408, rating: 5, comment: "کیفیت غذا خیلی خوب بود." },
    { reviewIndex: 409, rating: 4, comment: "خوب بود و ارزش سفارش دوباره دارد." },

    { reviewIndex: 410, rating: 5, comment: "خیلی خوشمزه بود." },
    { reviewIndex: 411, rating: 4, comment: "طعم خوبی داشت ولی کمی سرد شده بود." },
    { reviewIndex: 412, rating: 5, comment: "تازه و باکیفیت بود." },
    { reviewIndex: 413, rating: 3, comment: "طعم معمولی بود." },
    { reviewIndex: 414, rating: 5, comment: "خیلی راضی بودم." },
    { reviewIndex: 415, rating: 4, comment: "سفارش خوب و مرتب بود." },
    { reviewIndex: 416, rating: 5, comment: "طعمش واقعاً عالی بود." },
    { reviewIndex: 417, rating: 5, comment: "خیلی خوشمزه و تازه رسید." },
    { reviewIndex: 418, rating: 4, comment: "کیفیت مناسب بود." },
    { reviewIndex: 419, rating: 5, comment: "دوباره سفارش می‌دم." },

    { reviewIndex: 420, rating: 4, comment: "خوب بود و حجم مناسبی داشت." },
    { reviewIndex: 421, rating: 5, comment: "خیلی خوش‌طعم بود." },
    { reviewIndex: 422, rating: 5, comment: "غذا گرم و تازه بود." },
    { reviewIndex: 423, rating: 3, comment: "در حد انتظار بود." },
    { reviewIndex: 424, rating: 4, comment: "در مجموع راضی بودم." },
    { reviewIndex: 425, rating: 5, comment: "خیلی خوب بود و دوباره می‌گیرمش." },
    { reviewIndex: 426, rating: 5, comment: "کیفیت واقعاً خوبی داشت." },
    { reviewIndex: 427, rating: 4, comment: "طعم خوب بود، فقط کمی شور بود." },
    { reviewIndex: 428, rating: 5, comment: "خیلی خوشمزه بود." },
    { reviewIndex: 429, rating: 5, comment: "کاملاً راضی بودم." },

    { reviewIndex: 430, rating: 4, comment: "سفارش خوبی بود و مشکل خاصی نداشت." },
    { reviewIndex: 431, rating: 5, comment: "خیلی تازه و خوش‌طعم بود." },
    { reviewIndex: 432, rating: 3, comment: "بد نبود ولی می‌توانست بهتر باشد." },
    { reviewIndex: 433, rating: 5, comment: "طعم عالی داشت." },
    { reviewIndex: 434, rating: 4, comment: "حجم و کیفیت مناسب بود." },
    { reviewIndex: 435, rating: 5, comment: "خیلی خوب بود و سریع هم آماده شده بود." },
    { reviewIndex: 436, rating: 5, comment: "از انتخابم راضی بودم." },
    { reviewIndex: 437, rating: 4, comment: "در کل خوب بود." },
    { reviewIndex: 438, rating: 5, comment: "واقعاً خوشمزه بود." },
    { reviewIndex: 439, rating: 4, comment: "کیفیت قابل قبولی داشت." },

    { reviewIndex: 440, rating: 5, comment: "خیلی تازه بود و طعم خوبی داشت." },
    { reviewIndex: 441, rating: 4, comment: "خوب بود، فقط کمی دیر رسید." },
    { reviewIndex: 442, rating: 5, comment: "عالی بود و دوباره سفارش می‌دم." },
    { reviewIndex: 443, rating: 3, comment: "معمولی بود." },
    { reviewIndex: 444, rating: 5, comment: "خیلی خوشمزه و گرم بود." },
    { reviewIndex: 445, rating: 4, comment: "سفارش خوبی بود." },
    { reviewIndex: 446, rating: 5, comment: "کیفیت غذا خیلی خوب بود." },
    { reviewIndex: 447, rating: 5, comment: "از طعمش خیلی راضی بودم." },
    { reviewIndex: 448, rating: 4, comment: "خوب بود و حجمش مناسب بود." },
    { reviewIndex: 449, rating: 5, comment: "خیلی راضی بودم." },

    { reviewIndex: 450, rating: 4, comment: "طعم خوب و کیفیت مناسبی داشت." },
    { reviewIndex: 451, rating: 5, comment: "واقعاً خوشمزه بود." },
    { reviewIndex: 452, rating: 5, comment: "تازه و گرم به دستم رسید." },
    { reviewIndex: 453, rating: 3, comment: "بد نبود، ولی انتظار بیشتری داشتم." },
    { reviewIndex: 454, rating: 5, comment: "خیلی خوب بود و دوباره می‌گیرم." },
    { reviewIndex: 455, rating: 4, comment: "کیفیت خوبی داشت." },
    { reviewIndex: 456, rating: 5, comment: "طعمش عالی بود." },
    { reviewIndex: 457, rating: 4, comment: "در کل تجربه خوبی بود." },
    { reviewIndex: 458, rating: 5, comment: "خیلی خوش‌طعم و تازه بود." },
    { reviewIndex: 459, rating: 5, comment: "کاملاً راضی بودم." },

    { reviewIndex: 460, rating: 4, comment: "خوب بود و بسته‌بندی مناسبی داشت." },
    { reviewIndex: 461, rating: 5, comment: "خیلی خوشمزه بود." },
    { reviewIndex: 462, rating: 3, comment: "طعم معمولی داشت." },
    { reviewIndex: 463, rating: 5, comment: "خیلی تازه و باکیفیت بود." },
    { reviewIndex: 464, rating: 4, comment: "سفارش خوبی بود." },
    { reviewIndex: 465, rating: 5, comment: "طعم خیلی خوبی داشت و گرم رسید." },
    { reviewIndex: 466, rating: 5, comment: "از کیفیتش کاملاً راضی بودم." },
    { reviewIndex: 467, rating: 4, comment: "خوب بود، فقط کمی چرب بود." },
    { reviewIndex: 468, rating: 5, comment: "دوباره حتماً سفارش می‌دم." },
    { reviewIndex: 469, rating: 4, comment: "در مجموع رضایت‌بخش بود." },

    { reviewIndex: 470, rating: 5, comment: "خیلی خوشمزه و تازه بود." },
    { reviewIndex: 471, rating: 4, comment: "کیفیت خوب بود." },
    { reviewIndex: 472, rating: 5, comment: "واقعاً عالی بود." },
    { reviewIndex: 473, rating: 3, comment: "قابل قبول بود." },
    { reviewIndex: 474, rating: 5, comment: "طعمش خیلی خوب بود." },
    { reviewIndex: 475, rating: 4, comment: "حجم مناسب و کیفیت خوبی داشت." },
    { reviewIndex: 476, rating: 5, comment: "غذا گرم و مرتب رسید." },
    { reviewIndex: 477, rating: 5, comment: "خیلی راضی بودم." },
    { reviewIndex: 478, rating: 4, comment: "خوب بود و ارزش دوباره سفارش دادن دارد." },
    { reviewIndex: 479, rating: 5, comment: "طعم عالی داشت." },

    { reviewIndex: 480, rating: 4, comment: "سفارش خوب و قابل قبولی بود." },
    { reviewIndex: 481, rating: 5, comment: "خیلی تازه و خوشمزه بود." },
    { reviewIndex: 482, rating: 5, comment: "از کیفیت غذا راضی بودم." },
    { reviewIndex: 483, rating: 3, comment: "معمولی بود، شاید دفعه بعد غذای دیگری امتحان کنم." },
    { reviewIndex: 484, rating: 5, comment: "خیلی خوش‌طعم بود." },
    { reviewIndex: 485, rating: 4, comment: "خوب بود ولی کمی شور بود." },
    { reviewIndex: 486, rating: 5, comment: "کاملاً راضی بودم." },
    { reviewIndex: 487, rating: 4, comment: "در کل کیفیت مناسبی داشت." },
    { reviewIndex: 488, rating: 5, comment: "خیلی خوشمزه بود." },
    { reviewIndex: 489, rating: 5, comment: "دوباره سفارش می‌دم." },

    { reviewIndex: 490, rating: 4, comment: "طعم خوب و حجم مناسبی داشت." },
    { reviewIndex: 491, rating: 5, comment: "خیلی تازه بود." },
    { reviewIndex: 492, rating: 3, comment: "بد نبود ولی خیلی خاص نبود." },
    { reviewIndex: 493, rating: 5, comment: "واقعاً خوشمزه بود." },
    { reviewIndex: 494, rating: 4, comment: "کیفیت خوب بود و راضی بودم." },
    { reviewIndex: 495, rating: 5, comment: "خیلی خوب و گرم رسید." },
    { reviewIndex: 496, rating: 5, comment: "طعمش عالی بود." },
    { reviewIndex: 497, rating: 4, comment: "در مجموع سفارش خوبی بود." },
    { reviewIndex: 498, rating: 5, comment: "خیلی راضی بودم و دوباره سفارش می‌دم." },
    { reviewIndex: 499, rating: 2, comment: "متأسفانه این بار کیفیتش پایین‌تر از انتظارم بود." },

    // =================================================
    // RATING + COMMENT
    // 400 NEW REVIEWS
    // reviewIndex: 500 - 899
    // =================================================

    ...Array.from({ length: 400 }, (_, index) => {

        const reviewIndex = 500 + index;

        const ratings = [
            5, 5, 4, 5, 4,
            5, 3, 5, 4, 5,
            4, 5, 5, 4, 3,
            5, 4, 5, 5, 4
        ];

        const comments = [
            "غذا خیلی خوشمزه بود و از سفارشم راضی بودم.",
            "کیفیت غذا خوب بود و دوباره سفارش می‌دم.",
            "غذا تازه و گرم به دستم رسید.",
            "طعم غذا خیلی خوب بود و حجم مناسبی داشت.",
            "بسته‌بندی مرتب بود و غذا هم کیفیت خوبی داشت.",
            "در مجموع تجربه خوبی بود و از سفارشم راضی بودم.",
            "طعمش عالی بود و احتمالاً دوباره سفارش می‌دم.",
            "غذا خوش‌طعم و تازه بود.",
            "کیفیت غذا نسبت به قیمت مناسب بود.",
            "همه چیز خوب و مرتب به دستم رسید.",
            "غذا خیلی خوب آماده شده بود.",
            "از طعم غذا واقعاً راضی بودم.",
            "سفارش به‌موقع رسید و غذا هنوز گرم بود.",
            "حجم غذا مناسب بود و کیفیت خوبی داشت.",
            "طعم غذا دلچسب بود و دوستش داشتم.",
            "سفارش خوبی بود و مشکل خاصی نداشت.",
            "غذا تازه بود و طعم خوبی داشت.",
            "کیفیت این سفارش واقعاً رضایت‌بخش بود.",
            "خیلی خوشمزه بود و دوباره امتحانش می‌کنم.",
            "در کل سفارش قابل قبولی بود.",
            "غذا خوب بود و بسته‌بندی مناسبی داشت.",
            "طعم ادویه‌ها مناسب بود و غذا خوش‌طعم شده بود.",
            "از انتخابم راضی بودم و دوباره سفارش می‌دم.",
            "غذا گرم و مرتب رسید.",
            "کیفیت غذا خوب بود و مقدارش هم کافی بود.",
            "طعم خوبی داشت، فقط کمی شور بود.",
            "سفارش سریع رسید و کیفیت غذا هم خوب بود.",
            "هم طعم غذا خوب بود هم حجم مناسبی داشت.",
            "تجربه خوبی بود و از سفارش راضی بودم.",
            "غذا خوشمزه بود و تازگی خوبی داشت.",
            "همه چیز طبق سفارش و بدون مشکل رسید.",
            "طعم غذا خیلی خوب بود و ارزش سفارش دوباره داشت.",
            "غذا نسبت به انتظارم بهتر بود.",
            "کیفیت خوبی داشت و از سفارشم راضی بودم.",
            "غذا گرم رسید و مزه خوبی داشت.",
            "بسته‌بندی تمیز و مناسب بود.",
            "در مجموع غذای خوبی بود.",
            "طعمش خوب بود و حجمش هم مناسب بود.",
            "از کیفیت این سفارش خیلی راضی بودم.",
            "غذا تازه و خوش‌طعم بود.",
            "سفارش مرتب و کامل به دستم رسید.",
            "طعم غذا خوب بود و دوباره سفارش می‌دم.",
            "غذا کیفیت مناسبی داشت و راضی بودم.",
            "همه چیز خوب بود و سفارش بدون مشکل رسید.",
            "غذا خوشمزه بود و کیفیت قابل قبولی داشت.",
            "سفارش به موقع رسید و غذا گرم بود.",
            "طعم غذا عالی بود و خیلی دوستش داشتم.",
            "حجم و کیفیت غذا مناسب بود.",
            "در کل تجربه خوبی از این سفارش داشتم."
        ];

        return {
            reviewIndex,
            rating: ratings[index % ratings.length],
            comment: comments[index % comments.length]
        };

    })

];